name: hello-world
run-name: "Hello, World! from TS script"
on:
  push:
    branches:
      - "main"
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup nodejs
        uses: actions/setup-node@v4

      - name: Setup variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV

      - name: Install dependencies and build
        run: |
          npm install -g typescript ts-node
          npm install -D dotenv

      - name: Run TS script
        run: ts-node main.ts
