name: Triggers
run-name: GitHub Actions - Diferentes Triggers!
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.ts"
  issues:
    types: [opened, edited, closed]

  workflow_dispatch:
    inputs:
      favorite-language:
        description: "Favorite Programming Language"
        default: CoffeScript
        required: true
        type: choice
        options:
          - CoffeScript
          - TypeScript
          - Go
      name:
        description: "Name"
        required: true
        default: Roger
        type: string
  schedule:
    - cron: "15 22 * * *"
jobs:
  hello-manually:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20.9.0"

      - name: Install dependencies
        run: |
          npm install -g typescript ts-node
          npm install -D dotenv

      - name: Define name
        run: echo "USERNAME=${{ inputs.name }}" >> $GITHUB_ENV

      - name: Define Programming Language
        run: echo "LANGUAGE=${{ inputs.favorite-language }}" >> $GITHUB_ENV
      - name: Run bootstrap.ts script
        run: ts-node bootstrap.ts

  hello:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "20.9.0"

      - name: Install dependencies
        run: |
          npm install -g typescript ts-node
          npm install -D dotenv

      - name: Define variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV
      - name: Run main.ts script
        run: ts-node main.ts
