name: Contexts
run-name: "GitHub Action - Context"
on:
  push:
    branches: main

jobs:
  check-main:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploy on branch ${{ github.ref }}"
