name: Contexts
run-name: "GitHub Action - Context"
on:
  push:
    branches:
      - main

jobs:
  check-main:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        run: echo "Deploy on branch ${{ github.ref }}"

      - name: Display information
        env:
          BRANCH_NAME: ${{ github.ref }}
        run: |
          echo "${{ github.actor }} deployed on branch ${{ env.BRANCH_NAME }} in repo ${{ github.repository }}"
