name: Secret
run-name: "GitHub Action - Secret"
on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  CITY_NAME: Buenos Aires
jobs:
  greeting:
    if: ${{ github.event_name != 'workflow_dispatch'}}
    runs-on: ubuntu-latest
    env:
      GRETTING: Hey
    steps:
      - name: Gretting
        run: |
          echo "${{ env.GRETTING }} ${{ github.actor }}, ${{ env.CITY_NAME }} is beautiful!"
  lemon:
    if: ${{ github.event_name != 'push'}}
    runs-on: ubuntu-latest
    steps:
      - name: Lemon
        run: |
          echo "LEMON_TAG user: ${{ vars.LEMON_TAG }}"

        # vars.LEMON_TAG es una variable creada en GitHub
  secret:
    if: ${{ github.event_name != 'push'}}
    runs-on: ubuntu-latest
    steps:
      - name: Secret gretting
        run: |
          echo "${{ env.GRETTING }} ${{ vars.LEMON_TAG_v2 }}, your pass is ${{secrets.PASSWORD}}"
