name: triggers
run-name: "GitHub Action - Triggers"
on:
  push:
    branches:
      - "02-triggers"
  issues:
    types: [opened, labeled, edited, closed]

jobs:
  triggers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup nodejs
        uses: actions/setup-node@v4

      - name: Setup variable
        run: echo "USERNAME=${{ github.actor }}" >> $GITHUB_ENV

      - name: Install dependencies and build
        run: |
          yarn install
          yarn start
      - name: Run main.js
        run: npm run build && node dist/main.js
